openapi: 3.0.1
info:
  title: Opinion service
  description: Client API
  version: 1.0.0
servers:
  - url: 'https://localhost/'
tags:
  - name: question
    description: Manage questions
  - name: answer
    description: Manage answers
paths:
  /question:
    get:
      tags:
        - question
      summary: Request list of questions.
      operationId: questionsList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionsListRequest'
      responses:
        200:
          description: List of questions.
          content:
            application/json:
              schema:
                type: string

components:
  schemas:

    QuestionsListRequest:
      description: Request list of questions.
      properties:
        limit:
          type: integer


