# create question request
POST http://localhost:8080/question/create
Content-Type: application/json

{
  "className": "CreateQuestionRequest",
  "requestId": "123",
  "processingMode": "test",
  "question": {
    "questionId": "test-question-1",
    "title": "Main test question.",
    "content": "To Ktor or not to Ktor?",
    "author": "Bill Shake",
    "language": "English",
    "tags": ["test", "fun"]
  }
}

### request questions list
POST http://localhost:8080/question/list
Content-Type: application/json

{
  "className": "QuestionsRequest",
  "requestId": "2",
  "processingMode": "test",
  "pagination": {
    "objectsCount": 10,
    "objectId": "0",
    "relation": "before"
  }
}
